name: Auto-Merge Dependabot PRs on CI Success

on:
  workflow_dispatch:
  pull_request:
    types: [labeled, synchronize, opened, reopened, ready_for_review]
  check_suite:
    types: [completed]
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.merged == false
    steps:
      - name: Check CI status and Merge PR
        uses: actions/github-script@v5
        with:
          script: |
            const { data: statusCheck } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha,
            });
            const checksOK = statusCheck.check_runs.every(check => check.conclusion === 'success');
            if (checksOK) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
              });
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
