name: Auto-Merge Dependabot PRs on CI Success

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened, ready_for_review]
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Automerge PRs
        if: >
          github.actor == 'dependabot[bot]' &&
          github.event_name == 'check_suite' &&
          github.event.check_suite.conclusion == 'success'
        uses: actions/github-script@v5
        with:
          script: |
            const pr = await github.action.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            if (pr.data.mergeable && pr.data.user.login === 'dependabot[bot]') {
              await github.action.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
              });
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
