name: Auto-Merge Dependabot PRs on CI Success

on:
  workflow_dispatch:
  pull_request:
    types: [labeled, synchronize, opened, reopened, ready_for_review]
  check_suite:
    types: [completed]
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.merged == false
    steps:
      - name: Check CI status and Merge PR
        uses: actions/github-script@v5
        with:
          script: |
            const prNumber = context.issue.number;
            if (!prNumber) {
              console.log("No PR number found.");
              return;
            }

            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            const { data: listCheckRuns } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pullRequest.head.sha,
            });

            const allChecksPassed = listCheckRuns.check_runs.every(check => check.conclusion === 'success');

            if (allChecksPassed) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
              });
              console.log(`Merged PR #${prNumber}`);
            } else {
              console.log(`Not all checks passed for PR #${prNumber}`);
            }

          github-token: ${{ secrets.GITHUB_TOKEN }}
